# Generated by Django 5.1.15 on 2026-07-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_out_time_attendance_break_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='final_out',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Working', 'Working'), ('Absent', 'Absent')], default='Absent', max_length=20),
        ),
    ]
