# Generated by Django 5.1.15 on 2026-07-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_break_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
